insert into person(id,namesa,year_of_birthday,month_of_birthday,day_of_birthday) values(1,'martin',1991,8,7)
insert into person(id,namesa,year_of_birthday,month_of_birthday,day_of_birthday) values(2,'david',1992,7,21)
insert into person(id,namesa,year_of_birthday,month_of_birthday,day_of_birthday) values(3,'dennis',1993,10,15)
insert into person(id,namesa,year_of_birthday,month_of_birthday,day_of_birthday) values(4,'sophia',1994,8,8)
insert into person(id,namesa,year_of_birthday,month_of_birthday,day_of_birthday) values(5,'benny',1995,12,23)
insert into person(id,namesa,year_of_birthday,month_of_birthday,day_of_birthday,job,hobby,phone_number,address) values(6,'tony',1992,7,10,'officer','reading','010-2222-5555','서울')
insert into person(id,namesa,deleted) values(7,'andrew',true)